name: Try to setup PubForth and run simple program
on: [push, pull_request, workflow_dispatch]
jobs:
  Example:
    strategy:
      matrix: 
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup PubForth
        uses: visualdoj/setup-pubforth@main

      - name: Print PubForth version
        run: pubforth --version

      - name: Print PubForth help
        run: pubforth --long-help

      - name: Run command line evaluation
        run: pubforth --experimental -e "1 2 3 . . ."

      - name: Run program
        run: pubforth --experimental example.fs
